"""add is_revoked and expires_date to tokens

Revision ID: 1a2c62b8db3c
Revises: ec352d27f08c
Create Date: 2026-09-26 13:34:04.070410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2c62b8db3c'
down_revision: Union[str, Sequence[str], None] = 'ec352d27f08c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_revoked', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.VARCHAR(length=5), server_default=sa.text("'USER'"), nullable=False))

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('is_revoked')

    # ### end Alembic commands ###
